project:
  type: website

website:
  title: "Oluwaseun ePortfolio"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: CV
        href: cv.qmd
      - text: Projects
        href: projects/index.qmd 
      - text: Reflection
        href: reflection.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.scss